# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7598ad7ee9cfb2d0e25992ab9ffda62a1e67275caad37af6d18532f907bf1409cde42b9149ff32004bac37e463a97094e8e54b693791793afcfe99d768c4f70e

test:
  secret_key_base: 39fc245e6fe138bcac13ee8b23ce2e4424ef0b6141ff0f8fa9b5000f3ce5f61a879d585e7355edf96f8282b03ed2db61c8c70d75bcea21211f89427d1cf94bfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
